# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Parsing.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("font-family: Cambria;\n"
"background-color: #0F292F;")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MenuWidget = QtWidgets.QWidget(self.centralwidget)
        self.MenuWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.MenuWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.MenuWidget.setStyleSheet("QWidget{\n"
"background-color: #501F3A;\n"
"}\n"
"QPushButton{\n"
"background-color: #501F3A;\n"
"font-size: 28px;\n"
"color: #CCCCCC;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #CB2D6F;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #CB2D6F;\n"
"}")
        self.MenuWidget.setObjectName("MenuWidget")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.MenuWidget)
        self.gridLayout_47.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_47.setObjectName("gridLayout_47")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_47.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_47.addItem(spacerItem1, 0, 9, 1, 1)
        self.MainButtonWidget = QtWidgets.QWidget(self.MenuWidget)
        self.MainButtonWidget.setObjectName("MainButtonWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.MainButtonWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RemoveButton = QtWidgets.QPushButton(self.MainButtonWidget)
        self.RemoveButton.setMinimumSize(QtCore.QSize(50, 50))
        self.RemoveButton.setMaximumSize(QtCore.QSize(50, 50))
        self.RemoveButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.RemoveButton.setBaseSize(QtCore.QSize(0, 0))
        self.RemoveButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemoveButton.setIcon(icon)
        self.RemoveButton.setIconSize(QtCore.QSize(20, 20))
        self.RemoveButton.setShortcut("")
        self.RemoveButton.setObjectName("RemoveButton")
        self.horizontalLayout_6.addWidget(self.RemoveButton)
        self.FullSizeButton = QtWidgets.QPushButton(self.MainButtonWidget)
        self.FullSizeButton.setMinimumSize(QtCore.QSize(50, 50))
        self.FullSizeButton.setMaximumSize(QtCore.QSize(50, 50))
        self.FullSizeButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.FullSizeButton.setBaseSize(QtCore.QSize(0, 0))
        self.FullSizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/maximized.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FullSizeButton.setIcon(icon1)
        self.FullSizeButton.setIconSize(QtCore.QSize(20, 20))
        self.FullSizeButton.setObjectName("FullSizeButton")
        self.horizontalLayout_6.addWidget(self.FullSizeButton)
        self.CloseButton = QtWidgets.QPushButton(self.MainButtonWidget)
        self.CloseButton.setMinimumSize(QtCore.QSize(50, 50))
        self.CloseButton.setMaximumSize(QtCore.QSize(50, 50))
        self.CloseButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.CloseButton.setBaseSize(QtCore.QSize(0, 0))
        self.CloseButton.setStyleSheet("QPushButton:hover{\n"
"background-color: #FD1515;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #FD1515;\n"
"}")
        self.CloseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon2)
        self.CloseButton.setIconSize(QtCore.QSize(20, 20))
        self.CloseButton.setCheckable(False)
        self.CloseButton.setDefault(False)
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout_6.addWidget(self.CloseButton)
        self.gridLayout_47.addWidget(self.MainButtonWidget, 0, 12, 1, 1)
        self.ModeButtonWidget = QtWidgets.QWidget(self.MenuWidget)
        self.ModeButtonWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.ModeButtonWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ModeButtonWidget.setObjectName("ModeButtonWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ModeButtonWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ParserButton = QtWidgets.QPushButton(self.ModeButtonWidget)
        self.ParserButton.setMinimumSize(QtCore.QSize(50, 50))
        self.ParserButton.setMaximumSize(QtCore.QSize(50, 50))
        self.ParserButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/data_download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ParserButton.setIcon(icon3)
        self.ParserButton.setIconSize(QtCore.QSize(40, 40))
        self.ParserButton.setObjectName("ParserButton")
        self.horizontalLayout_7.addWidget(self.ParserButton)
        self.gridLayout_47.addWidget(self.ModeButtonWidget, 0, 4, 1, 1)
        self.HomeButtonWidget = QtWidgets.QWidget(self.MenuWidget)
        self.HomeButtonWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.HomeButtonWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.HomeButtonWidget.setObjectName("HomeButtonWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.HomeButtonWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.HomeButton = QtWidgets.QPushButton(self.HomeButtonWidget)
        self.HomeButton.setMinimumSize(QtCore.QSize(50, 50))
        self.HomeButton.setMaximumSize(QtCore.QSize(50, 50))
        self.HomeButton.setStyleSheet("QPushButton:hover{\n"
"background-color: none;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: none;\n"
"}")
        self.HomeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeButton.setIcon(icon4)
        self.HomeButton.setIconSize(QtCore.QSize(30, 30))
        self.HomeButton.setObjectName("HomeButton")
        self.verticalLayout_3.addWidget(self.HomeButton)
        self.gridLayout_47.addWidget(self.HomeButtonWidget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_47.addItem(spacerItem2, 0, 1, 1, 1)
        self.ModelLabel = QtWidgets.QLabel(self.MenuWidget)
        self.ModelLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.ModelLabel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ModelLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ModelLabel.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 40px;\n"
"font-family: Century Schoolbook;\n"
"}")
        self.ModelLabel.setText("")
        self.ModelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelLabel.setObjectName("ModelLabel")
        self.gridLayout_47.addWidget(self.ModelLabel, 0, 2, 1, 1)
        self.TournamentLabel = QtWidgets.QLabel(self.MenuWidget)
        self.TournamentLabel.setEnabled(True)
        self.TournamentLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.TournamentLabel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.TournamentLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TournamentLabel.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 40px;\n"
"font-family: Century Schoolbook;\n"
"}")
        self.TournamentLabel.setText("")
        self.TournamentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TournamentLabel.setObjectName("TournamentLabel")
        self.gridLayout_47.addWidget(self.TournamentLabel, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_47.addItem(spacerItem3, 0, 11, 1, 1)
        self.gridLayout.addWidget(self.MenuWidget, 0, 0, 1, 2)
        self.SizeGripWidget = QtWidgets.QWidget(self.centralwidget)
        self.SizeGripWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.SizeGripWidget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SizeGripWidget.setStyleSheet("QWidget{\n"
"background-color: none;\n"
"}")
        self.SizeGripWidget.setObjectName("SizeGripWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SizeGripWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(970, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.size_grip = QtWidgets.QWidget(self.SizeGripWidget)
        self.size_grip.setEnabled(True)
        self.size_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.size_grip.setSizeIncrement(QtCore.QSize(20, 20))
        self.size_grip.setBaseSize(QtCore.QSize(20, 20))
        self.size_grip.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.size_grip.setAutoFillBackground(False)
        self.size_grip.setStyleSheet("background-color: none;\n"
"border:none;\n"
"")
        self.size_grip.setObjectName("size_grip")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.size_grip)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.size_grip)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/WindowArrow.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.size_grip)
        self.gridLayout.addWidget(self.SizeGripWidget, 3, 1, 1, 1)
        self.TournamentWidget = QtWidgets.QWidget(self.centralwidget)
        self.TournamentWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.TournamentWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.TournamentWidget.setStyleSheet("QWidget{\n"
"background-color: #501F3A;\n"
"}\n"
"QPushButton{\n"
"background-color: #501F3A;\n"
"font-size: 28px;\n"
"color: #CCCCCC;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #CB2D6F;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #CB2D6F;\n"
"}")
        self.TournamentWidget.setObjectName("TournamentWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.TournamentWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ESPNButton = QtWidgets.QPushButton(self.TournamentWidget)
        self.ESPNButton.setMinimumSize(QtCore.QSize(50, 50))
        self.ESPNButton.setMaximumSize(QtCore.QSize(50, 50))
        self.ESPNButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/espn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ESPNButton.setIcon(icon5)
        self.ESPNButton.setIconSize(QtCore.QSize(50, 50))
        self.ESPNButton.setObjectName("ESPNButton")
        self.verticalLayout_6.addWidget(self.ESPNButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.TournamentButtonWidget = QtWidgets.QWidget(self.TournamentWidget)
        self.TournamentButtonWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.TournamentButtonWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TournamentButtonWidget.setObjectName("TournamentButtonWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TournamentButtonWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NBAButton = QtWidgets.QPushButton(self.TournamentButtonWidget)
        self.NBAButton.setMinimumSize(QtCore.QSize(50, 50))
        self.NBAButton.setMaximumSize(QtCore.QSize(50, 50))
        self.NBAButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/nba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NBAButton.setIcon(icon6)
        self.NBAButton.setIconSize(QtCore.QSize(40, 40))
        self.NBAButton.setObjectName("NBAButton")
        self.verticalLayout.addWidget(self.NBAButton)
        self.NHLButton = QtWidgets.QPushButton(self.TournamentButtonWidget)
        self.NHLButton.setMinimumSize(QtCore.QSize(50, 50))
        self.NHLButton.setMaximumSize(QtCore.QSize(50, 50))
        self.NHLButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/nhl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NHLButton.setIcon(icon7)
        self.NHLButton.setIconSize(QtCore.QSize(40, 40))
        self.NHLButton.setObjectName("NHLButton")
        self.verticalLayout.addWidget(self.NHLButton)
        self.NFLButton = QtWidgets.QPushButton(self.TournamentButtonWidget)
        self.NFLButton.setMinimumSize(QtCore.QSize(50, 50))
        self.NFLButton.setMaximumSize(QtCore.QSize(50, 50))
        self.NFLButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/nfl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NFLButton.setIcon(icon8)
        self.NFLButton.setIconSize(QtCore.QSize(60, 60))
        self.NFLButton.setObjectName("NFLButton")
        self.verticalLayout.addWidget(self.NFLButton)
        self.MLBButton = QtWidgets.QPushButton(self.TournamentButtonWidget)
        self.MLBButton.setMinimumSize(QtCore.QSize(50, 50))
        self.MLBButton.setMaximumSize(QtCore.QSize(50, 50))
        self.MLBButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/mlb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MLBButton.setIcon(icon9)
        self.MLBButton.setIconSize(QtCore.QSize(80, 80))
        self.MLBButton.setObjectName("MLBButton")
        self.verticalLayout.addWidget(self.MLBButton)
        self.verticalLayout_6.addWidget(self.TournamentButtonWidget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.BookmakerButtonWidget = QtWidgets.QWidget(self.TournamentWidget)
        self.BookmakerButtonWidget.setMinimumSize(QtCore.QSize(50, 150))
        self.BookmakerButtonWidget.setMaximumSize(QtCore.QSize(50, 150))
        self.BookmakerButtonWidget.setObjectName("BookmakerButtonWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.BookmakerButtonWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BetboomButton = QtWidgets.QPushButton(self.BookmakerButtonWidget)
        self.BetboomButton.setMinimumSize(QtCore.QSize(50, 50))
        self.BetboomButton.setMaximumSize(QtCore.QSize(50, 50))
        self.BetboomButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/betboom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BetboomButton.setIcon(icon10)
        self.BetboomButton.setIconSize(QtCore.QSize(40, 40))
        self.BetboomButton.setObjectName("BetboomButton")
        self.verticalLayout_8.addWidget(self.BetboomButton)
        self.WinlineButton = QtWidgets.QPushButton(self.BookmakerButtonWidget)
        self.WinlineButton.setMinimumSize(QtCore.QSize(50, 50))
        self.WinlineButton.setMaximumSize(QtCore.QSize(50, 50))
        self.WinlineButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/winline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WinlineButton.setIcon(icon11)
        self.WinlineButton.setIconSize(QtCore.QSize(40, 40))
        self.WinlineButton.setObjectName("WinlineButton")
        self.verticalLayout_8.addWidget(self.WinlineButton)
        self.verticalLayout_6.addWidget(self.BookmakerButtonWidget)
        self.gridLayout.addWidget(self.TournamentWidget, 2, 0, 2, 1)
        self.MainWidget = QtWidgets.QWidget(self.centralwidget)
        self.MainWidget.setStyleSheet("QScrollBar:vertical{\n"
"    background-color: #CB2D6F;\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical{\n"
"background-color: #501F3A;\n"
"border: none;\n"
"margin: 15px 0 15px 0;\n"
"width: 22px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"background-color: #CB2D6F;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: #AB275C;\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"background-color: #AB275C;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"border: none;\n"
"background-color: #CB2D6F;\n"
"height: 15px;\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"background-color: #AB275C;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"background-color: #AB275C;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"border: none;\n"
"background-color: #CB2D6F;\n"
"height: 15px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"background-color: #AB275C;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed{\n"
"background-color: #AB275C;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"background-color: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"background-color: none;\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:horizontal{\n"
"border: 1px transparent #2A2929;\n"
"border-radius: 4px;\n"
"background-color: #501F3A; \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background-color: #CB2D6F;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"background-color: #AB275C;\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"background-color: #AB275C;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: none;\n"
"      background: none;\n"
"      color: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"background: none;\n"
"}")
        self.MainWidget.setObjectName("MainWidget")
        self.gridLayout.addWidget(self.MainWidget, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.CloseButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import resourse_rc
